# Generated by Django 5.0.6 on 2024-06-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='dispositivo',
            field=models.IntegerField(),
        ),
    ]
